name: Package Open Graph Data Science (GDS)

on:
  push:
    branches:
      - main
    # Only run on opengds.version changes or when this workflow changes
    paths:
      - ".github/workflows/package-opengds.yml"
  pull_request:
    branches:
      - main
    # Only run on opengds.version changes or when this workflow changes
    paths:
      - ".github/workflows/package-opengds.yml"

jobs:
  package:
    strategy:
      matrix:
        include:
          - java-version: 11.0.19 # Java 11 is required for Neo4j v4.x
            neo4j-version: 4.4.23
            gds-version: 2.4.3
          - java-version: 17.0.7 # Java 17 is required for Neo4j >= v5.x
            neo4j-version: 5.9.0
            gds-version: 2.4.3
    uses: ./.github/workflows/prepare-opengds.yml
    with:
      java-version: ${{ matrix.java-version }}
      neo4j-version: ${{ matrix.neo4j-version }}
      gds-version: ${{ matrix.gds-version }}
