name: Package Open Graph Data Science (GDS)

on:
  push:
    branches:
      - main
    # Only run on opengds.version changes or when this workflow changes
    paths:
      - ".github/workflows/package-opengds.yml"
  pull_request:
    branches:
      - main
    # Only run on opengds.version changes or when this workflow changes
    paths:
      - ".github/workflows/package-opengds.yml"

jobs:
  package:
    strategy:
      matrix:
        include:
          # Neo4j v4 support dropped with graph-data-science >= v2.7.0
          # - java-version = 11.0.19 # Java 11 is required for Neo4j v4.x
          #   neo4j-version = 4.4.42
          #   gds-version = 2.6.0
          # Neo4j v5 support dropped with graph-data-science >= v2.14.0
          # - java-version = 17.0.6 # Java 17 is required for Neo4j v5.x
          #   neo4j-version = 5.26.5
          #   gds-version = 2.14.0
          - java-version: 21.0.6 # Java 21 is required for Neo4j >= v2025.x
            neo4j-version: 2025.04.0
            gds-version: 2.17.1
    uses: ./.github/workflows/prepare-opengds.yml
    with:
      java-version: ${{ matrix.java-version }}
      neo4j-version: ${{ matrix.neo4j-version }}
      gds-version: ${{ matrix.gds-version }}
