name: Release Open Graph Data Science (GDS) Package

on:
  push:
    tags:
      - "**"

jobs:
  prepare-release:
    strategy:
      matrix:
        include:
          # Neo4j v4 support dropped with graph-data-science >= v2.7.0
          # - java-version = 11.0.19
          #   neo4j-version = 4.4.42
          #   gds-version = 2.6.0
          # Neo4j v5 support dropped with graph-data-science >= v2.14.0
          # - java-version = 17.0.6 # Java 17 is required for Neo4j v5.x
          #   neo4j-version = 5.26.5
          #   gds-version = 2.14.0
          - java-version: 21.0.6 # Java 21 is required for Neo4j >= v2025.x
            neo4j-version: 2025.09.0
            gds-version: 2.22.0
    uses: ./.github/workflows/prepare-opengds.yml
    with:
      java-version: ${{ matrix.java-version }}
      neo4j-version: ${{ matrix.neo4j-version }}
      gds-version: ${{ matrix.gds-version }}
      
  release:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: [prepare-release]
    runs-on: ubuntu-latest
    steps:
      - name: Download previously prepared artifacts
        uses: actions/download-artifact@v5

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ github.ref_name }} OpenGDS
          body: |
            # Open Neo4j Graph Data Science (OpenGDS) ${{ github.ref_name }} Plugin Package
            
            This is only the automated packaging of the open sourced part of [Neo4j's Graph Data Science](https://github.com/neo4j/graph-data-science) plugin.  
            Please visit [graph-data-science](https://github.com/neo4j/graph-data-science) for more details.  

            ## Installation 
             
            Copy the JAR that suits your installation into the plugin directory of Neo4j.  
            See [Neo4j Graph Data Science Installation](https://neo4j.com/docs/graph-data-science/current/installation) for more details.  
            
            ## Notes

            :warning: This repository is only meant to be a personal workaround for the missing official OpenGDS plugin release artifacts.  
            :warning: It is strongly recommended to switch to an official OpenGDS package as soon there is one.

            ---
          generate_release_notes: true
          token: ${{ secrets.RELEASE_TOKEN }}
          files: "**/*.jar"
